//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlindRiverContext : DbContext
    {
        public BlindRiverContext()
            : base("name=BlindRiverContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AskBlindRiver> AskBlindRivers { get; set; }
        public DbSet<Calculator> Calculators { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<DoctorAppointment> DoctorAppointments { get; set; }
        public DbSet<DoctorAvailableDate> DoctorAvailableDates { get; set; }
        public DbSet<DoctorAvailableTime> DoctorAvailableTimes { get; set; }
        public DbSet<Donation> Donations { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<FAQ> FAQs { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<PaymentInfo> PaymentInfoes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Severity> Severities { get; set; }
        public DbSet<VolunteerInfo> VolunteerInfoes { get; set; }
        public DbSet<VoluteerPost> VoluteerPosts { get; set; }
        public DbSet<PatientVisitingHour> PatientVisitingHours { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<ReviewCategory> ReviewCategories { get; set; }
        public DbSet<VisitingSchedule> VisitingSchedules { get; set; }

        public DbSet<Event> Events { get; set; }
        public DbSet<EventMemberStatu> EventMemberStatus { get; set; }

        public DbSet<Patient> Patients { get; set; }
    }
}
