//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAvailableDate
    {
        public DoctorAvailableDate()
        {
            this.DoctorAvailableTimes = new HashSet<DoctorAvailableTime>();
        }
    
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<DoctorAvailableTime> DoctorAvailableTimes { get; set; }
    }
}
