//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DonationDate { get; set; }
        public int DonationAmount { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Gender { get; set; }
    
        public virtual City City { get; set; }
    }
}
