//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventMemberStatus = new HashSet<EventMemberStatu>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime DateTime { get; set; }
        public int NumberInvited { get; set; }
        public int NumberGoing { get; set; }
        public int NumberDeclined { get; set; }
        public bool Active { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public int EnteredBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<EventMemberStatu> EventMemberStatus { get; set; }
    }
}
