//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string EntranceName { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longtitude { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
