//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Contacts = new HashSet<Contact>();
            this.Doctors = new HashSet<Doctor>();
            this.DoctorAvailableDates = new HashSet<DoctorAvailableDate>();
            this.Facilities = new HashSet<Facility>();
            this.FAQs = new HashSet<FAQ>();
            this.Locations = new HashSet<Location>();
            this.Services = new HashSet<Service>();
            this.Severities = new HashSet<Severity>();
            this.VoluteerPosts = new HashSet<VoluteerPost>();
            this.PatientVisitingHours = new HashSet<PatientVisitingHour>();
            this.Reviews = new HashSet<Review>();
            this.ReviewCategories = new HashSet<ReviewCategory>();
            this.VisitingSchedules = new HashSet<VisitingSchedule>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public System.DateTime JoinedDay { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string MiddleName { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<DoctorAvailableDate> DoctorAvailableDates { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<FAQ> FAQs { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Severity> Severities { get; set; }
        public virtual ICollection<VoluteerPost> VoluteerPosts { get; set; }
        public virtual ICollection<PatientVisitingHour> PatientVisitingHours { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<ReviewCategory> ReviewCategories { get; set; }
        public virtual ICollection<VisitingSchedule> VisitingSchedules { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
