//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientVisitingHours = new HashSet<PatientVisitingHour>();
            this.VisitingSchedules = new HashSet<VisitingSchedule>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<PatientVisitingHour> PatientVisitingHours { get; set; }
        public virtual ICollection<VisitingSchedule> VisitingSchedules { get; set; }
    }
}
