//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitingHour
    {
        public PatientVisitingHour()
        {
            this.VisitingSchedules = new HashSet<VisitingSchedule>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public System.DateTime VisitingDateFrom { get; set; }
        public Nullable<System.DateTime> VisitingDateTo { get; set; }
        public Nullable<System.TimeSpan> VisitingHourFrom { get; set; }
        public Nullable<System.TimeSpan> VisitingHourTo { get; set; }
        public int MaxTimeSpan { get; set; }
        public int TimeSpanBetweenVisit { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<VisitingSchedule> VisitingSchedules { get; set; }
    }
}
