//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int ReviewCategoryId { get; set; }
        public int DoctorId { get; set; }
        public Nullable<int> Punctuality { get; set; }
        public Nullable<int> Helpfullness { get; set; }
        public Nullable<int> Knowledge { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Pros { get; set; }
        public string Cons { get; set; }
        public string Advice { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Member Member { get; set; }
        public virtual ReviewCategory ReviewCategory { get; set; }
    }
}
