//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Role
    {
        public Role()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
