//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLINDRIVER_TEAM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerInfo
    {
        public int Id { get; set; }
        public System.DateTime ApplyDate { get; set; } = DateTime.Now;
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Description { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int VolunteerPostId { get; set; }
    
        public virtual City City { get; set; }
        public virtual VoluteerPost VoluteerPost { get; set; }
    }
}
